//@Library('Jenkins') _

pipeline {
  agent {
        docker {
            image 'docker:24.0.6-cli'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
  environment {
       IMAGE_NAME = 'srujeeth47/http-echo-test'
     }
  stages {
    stage('Checkout') {
      steps { 
         git url: 'https://github.com/hashicorp/http-echo.git'
	     }		
    }
    stage('Build & Push Image') {
      steps { 
           sh """
        docker build -t ${IMAGE_NAME} .
        docker tag ${IMAGE_NAME} ${IMAGE_NAME}
        docker push ${IMAGE_NAME}
    """
		
	     }

    }
    stage('Run & Health Check') {
      steps { 
 	     sh """
        docker run -d --name http-echo -p 5678:5678 ${IMAGE_NAME}
        sleep 5
        curl -f http://localhost:5678 || echo 'Healthcheck failed'
    """
     }
    }
  }
  post {

    always {
      echo " Cleaning up ..."
      sh 'docker rm -f http-echo || true'
      sh 'docker rmi $IMAGE_NAME|| true'
    }
  }
}