//@Library('Jenkins') _

pipeline {
  agent any
  environment {
       IMAGE_NAME = 'srujeeth47/http-echo-test'
     }
  stages {
    stage('Checkout') {
      steps { 
         git url: 'https://github.com/hashicorp/http-echo.git'
	     }		
    }
    stage('Build & Push Image') {
      steps { dockerUtils.buildAndPushDockerImage(IMAGE_NAME) }
    }
    stage('Run & Health Check') {
      steps { dockerUtils..runHealthcheck(IMAGE_NAME) }
    }
  }
  post {

    always {
      echo " Cleaning up ..."
      sh 'docker rm -f http-echo || true'
      sh 'docker rmi $IMAGE_NAME|| true'
    }
  }
}